In [1]:
#libraries
import pandas as pd

In [4]:
#importing file
df=pd.read_csv("/content/Aviation_KPIs_Dataset.csv")

In [3]:
df.head()

,Flight Number,Scheduled Departure Time,Actual Departure Time,Delay (Minutes),Aircraft Utilization (Hours/Day),Turnaround Time (Minutes),Load Factor (%),Fleet Availability (%),Maintenance Downtime (Hours),Fuel Efficiency (ASK),Revenue (USD),Operating Cost (USD),Net Profit Margin (%),Ancillary Revenue (USD),Debt-to-Equity Ratio,Revenue per ASK,Cost per ASK,Profit (USD)
0,FL885,2024-05-20 11:51:21,2024-07-10 02:38:54,50,12.36,115,79.18,96.24,9.21,4.15,10953.75,27847.59,17.90,1058.68,2.46,2639.46,6710.26,-16893.84
1,FL930,2024-01-23 06:56:23,2024-07-07 02:53:44,27,14.53,83,98.59,80.49,1.55,3.93,31597.25,1564.41,7.70,2941.32,2.89,8040.01,398.07,30032.84
2,FL478,2024-05-30 09:18:39,2024-12-05 01:00:54,108,10.73,87,67.44,97.90,2.06,4.26,13700.27,30494.88,5.84,1920.45,1.34,3216.03,7158.42,-16794.61
3,FL637,2024-08-15 05:21:47,2024-09-21 13:23:42,64,15.10,99,69.01,80.17,6.85,4.13,39913.01,13444.09,24.09,3167.79,0.60,9664.17,3255.23,26468.92
4,FL318,2024-07-25 15:29:58,2024-03-21 15:05:54,30,13.46,114,50.36,82.23,7.30,4.97,11531.48,34668.98,7.18,619.80,0.84,2320.22,6975.65,-23137.50

In [7]:
#data auditing
#missing values
df.isnull().sum()

Flight Number                       0
Scheduled Departure Time            0
Actual Departure Time               0
Delay (Minutes)                     0
Aircraft Utilization (Hours/Day)    0
Turnaround Time (Minutes)           0
Load Factor (%)                     0
Fleet Availability (%)              0
Maintenance Downtime (Hours)        0
Fuel Efficiency (ASK)               0
Revenue (USD)                       0
Operating Cost (USD)                0
Net Profit Margin (%)               0
Ancillary Revenue (USD)             0
Debt-to-Equity Ratio                0
Revenue per ASK                     0
Cost per ASK                        0
Profit (USD)                        0
dtype: int64

In [9]:
#duplecates
df.duplicated().sum()

np.int64(0)

In [10]:
#Create the cost to revenue
df['Cost_to_Revenue_Ratio'] = df['Operating Cost (USD)'] / df['Revenue (USD)']

In [11]:
#Find profitable or loss
df['Is_Profitable'] = (df['Profit (USD)'] > 0).astype(int)

In [17]:
print(df[['Revenue (USD)', 'Operating Cost (USD)', 'Cost_to_Revenue_Ratio', 'Profit (USD)', 'Is_Profitable']].head(5))

   Revenue (USD)  Operating Cost (USD)  Cost_to_Revenue_Ratio  Profit (USD)  \
0       10953.75              27847.59               2.542288     -16893.84
1       31597.25               1564.41               0.049511      30032.84
2       13700.27              30494.88               2.225860     -16794.61
3       39913.01              13444.09               0.336835      26468.92
4       11531.48              34668.98               3.006464     -23137.50

   Is_Profitable
0              0
1              1
2              0
3              1
4              0